physics:
- doc_id: 4
  doc_name: Grade 12 Physics Unit 1 2 en
  doc_path: C:\Users\PK\Desktop\SenzeMate Bootcamp\Project\ai-grading-system\doc\subjects\Grade
    12 Physics Unit 1 2 en.pdf
  md_path: doc\subjects\markdown\[4]_Grade 12 Physics Unit 1 2 en.md
  converted_date: '2026-01-11T21:09:32.596029'
- doc_id: 5
  doc_name: Grade 12 Physics Unit 1 2 en.pdf
  doc_path: C:\Users\PK\Desktop\SenzeMate Bootcamp\Project\ai-grading-system\doc\subjects\Grade
    12 Physics Unit 1 2 en.pdf
  md_path: doc\subjects\markdown\[5]_Grade 12 Physics Unit 1 2 en.md
  converted_date: '2026-01-11T21:14:37.287201'
